# @package _group_

batch_size: 8
prune: True
n_iterations: 5
proposal_checkpoint: data/models/hres_gibson_def/proposal.ckpt
loss_margin: 0.3
exp_base_name: pipeline_soft
exp_name: dropout_soft_sgd_dropout
lr: 0.001
optimizer: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True
  weight_decay: 5e-4

use_coco: False
transform_type: strong_image
dropout_p: 0.1
teacher_momentum: 0.99
temperature: 2
pipeline: Pipeline
student_model: SoftDropoutMultiStageModel
consensus: vanilla
alpha: 0.7
loss_weights:
  loss_cls: 1.0
  loss_soft: 1.0
  contrastive_loss: 0.0
  loss_mask: 1.0

