# @package _group_

batch_size: 4
prune: True
n_iterations: 1
thr: 0.7
proposal_checkpoint: data/models/hres_gibson_def/proposal.ckpt
loss_margin: 0.3
exp_base_name: pipeline_soft_constrastive
exp_name_training: soft_ce_sgd
lr: 0.0001
optimizer: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True
  weight_decay: 5e-4

transform_type: strong_image
teacher_momentum: 0.99
temperature: 1
pipeline: Pipeline
student_model: SoftMultiStageModel
use_coco: False
consensus: semantic_map
alpha: 0.7
loss_weights:
  loss_cls: 1.0
  loss_soft: 1.0
  contrastive_loss: 1.0
  loss_mask: 1.0

consecutive_obs: 2
weight_sampler: False
update_target: True
reinit_online: False
ema: False