# @package _group_

batch_size: 8
prune: True
n_iterations: 25
proposal_checkpoint: data/models/hres_gibson_def/proposal.ckpt
loss_margin: 0.3
exp_base_name: pipeline_soft
exp_name: ground_truth_sgd_focal
lr: 0.0001
optimizer: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True
transform_type: strong_image
teacher_momentum: 0.99
temperature: 2
pipeline: GTPipeline
student_model: FocalOnlyMultiStageModel
consensus: logits
alpha: 0.9
loss_weights:
  loss_cls: 1.0
  loss_soft: 1.0
  contrastive_loss: 0.0
  loss_mask: 1.0

