# @package _group_

batch_size: 16
prune: True
n_iterations: 50
proposal_checkpoint: data/models/hres_gibson_def/proposal.ckpt
loss_margin: 0.3
exp_base_name: pipeline_soft
exp_name: online_pseudo_ce
lr: 0.0001
optimizer: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True
  weight_decay: 5e-4

use_coco: False
dropout_p: 0.4
transform_type: strong_image
teacher_momentum: 0.99
temperature: 1
pipeline: OnlinePipeline
student_model: MultiStageModel
consensus: vanilla
alpha: 0.1
loss_weights:
  loss_cls: 1.0
  loss_soft: 1.0
  contrastive_loss: 0.0
  loss_mask: 1.0
freeze_teacher: False
