# @package _group_

batch_size: 16
prune: True
n_iterations: 50
proposal_checkpoint: data/models/hres_gibson_def/proposal.ckpt
loss_margin: 0.3
exp_base_name: pipeline_soft
exp_name: pipeline_soft
lr: 0.0001
optimizer: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True

teacher_momentum: 0.99
temperature: 2

consensus: logits
alpha: 0.9
loss_weights:
  loss_cls: 0.0
  loss_soft: 0.0
  contrastive_loss: 1.0
  loss_mask: 0.0


