# @package _group_

batch_size: 16
prune: True
n_iterations: 50
proposal_checkpoint: data/models/hres_gibson_def/proposal.ckpt
loss_margin: 0.3
exp_base_name: pipeline_soft
exp_name: dropout_online_dropout_sgd
lr: 0.00001
optimizer: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True

transform_type: none
dropout_p: 0.2
teacher_momentum: 0.99
temperature: 2
pipeline: OnlinePipeline
student_model: SoftDropoutMultiStageModel
consensus: vanilla
alpha: 0.7
loss_weights:
  loss_cls: 1.0
  loss_soft: 1.0
  contrastive_loss: 0.0
  loss_mask: 1.0

